// <auto-generated />
using System;
using EFEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFEntity.Migrations
{
    [DbContext(typeof(HR_DBDbContent))]
    partial class HR_DBDbContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFEntity.bonus", b =>
                {
                    b.Property<int>("Bon_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bonus_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bonus_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Bonus_worth")
                        .HasColumnType("float");

                    b.Property<int>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Bon_id");

                    b.ToTable("bonus");
                });

            modelBuilder.Entity("EFEntity.config_file_first_kind", b =>
                {
                    b.Property<int>("Ffk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_salary_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_sale_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ffk_id");

                    b.ToTable("config_file_first_kind");
                });

            modelBuilder.Entity("EFEntity.config_file_second_kind", b =>
                {
                    b.Property<int>("Fsk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_salary_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_sale_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Fsk_id");

                    b.ToTable("config_file_second_kind");
                });

            modelBuilder.Entity("EFEntity.config_file_third_kind", b =>
                {
                    b.Property<int>("Ftk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_is_retail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_sale_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ftk_id");

                    b.ToTable("config_file_third_kind");
                });

            modelBuilder.Entity("EFEntity.config_major", b =>
                {
                    b.Property<int>("Mak_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test_amount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mak_id");

                    b.ToTable("config_major");
                });

            modelBuilder.Entity("EFEntity.config_major_kind", b =>
                {
                    b.Property<int>("Mfk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mfk_id");

                    b.ToTable("config_major_kind");
                });

            modelBuilder.Entity("EFEntity.config_primary_key", b =>
                {
                    b.Property<int>("Prk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primary_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Primary_key_status")
                        .HasColumnType("bit");

                    b.Property<string>("Primary_key_table")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Prk_id");

                    b.ToTable("config_primary_key");
                });

            modelBuilder.Entity("EFEntity.config_public_char", b =>
                {
                    b.Property<int>("Pbc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attribute_kind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attribute_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pbc_id");

                    b.ToTable("config_public_char");
                });

            modelBuilder.Entity("EFEntity.config_question_first_kind", b =>
                {
                    b.Property<int>("Qfk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Qfk_id");

                    b.ToTable("config_question_first_kind");
                });

            modelBuilder.Entity("EFEntity.config_question_second_kind", b =>
                {
                    b.Property<int>("Qsk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Qsk_id");

                    b.ToTable("config_question_second_kind");
                });

            modelBuilder.Entity("EFEntity.engage_answer", b =>
                {
                    b.Property<int>("Ans_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exam_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_idcard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interview_id")
                        .HasColumnType("int");

                    b.Property<string>("Major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Resume_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Test_time")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total_point")
                        .HasColumnType("float");

                    b.Property<string>("Use_time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ans_id");

                    b.ToTable("engage_answer");
                });

            modelBuilder.Entity("EFEntity.engage_answer_details", b =>
                {
                    b.Property<int>("And_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subject_id")
                        .HasColumnType("int");

                    b.HasKey("And_id");

                    b.ToTable("engage_answer_details");
                });

            modelBuilder.Entity("EFEntity.engage_exam", b =>
                {
                    b.Property<int>("Exa_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exam_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Limite_time")
                        .HasColumnType("int");

                    b.Property<string>("Major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Exa_id");

                    b.ToTable("engage_exam");
                });

            modelBuilder.Entity("EFEntity.engage_exam_details", b =>
                {
                    b.Property<int>("Exd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exam_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Question_amount")
                        .HasColumnType("int");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Exd_id");

                    b.ToTable("engage_exam_details");
                });

            modelBuilder.Entity("EFEntity.engage_interview", b =>
                {
                    b.Property<int>("Ein_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Check_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EQ_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foreign_language_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IQ_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interview_amount")
                        .HasColumnType("int");

                    b.Property<string>("Interview_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interview_status")
                        .HasColumnType("int");

                    b.Property<string>("Multi_quality_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Native_language_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Registe_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response_speed_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Resume_id")
                        .HasColumnType("int");

                    b.HasKey("Ein_id");

                    b.ToTable("engage_interview");
                });

            modelBuilder.Entity("EFEntity.engage_major_release", b =>
                {
                    b.Property<int>("Mre_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Engage_required")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engage_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Human_amount")
                        .HasColumnType("int");

                    b.Property<string>("Major_describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mre_id");

                    b.ToTable("engage_major_release");
                });

            modelBuilder.Entity("EFEntity.engage_resume", b =>
                {
                    b.Property<int>("Res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachment_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Demand_salary_standard")
                        .HasColumnType("float");

                    b.Property<string>("Engage_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Human_age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Human_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Human_birthplace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_college")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_educated_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_educated_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Human_educated_years")
                        .HasColumnType("int");

                    b.Property<string>("Human_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_history_records")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_homephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_idcard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_party")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_specility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interview_status")
                        .HasColumnType("int");

                    b.Property<string>("Pass_checkComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pass_check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Pass_check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pass_checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass_passComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Pass_regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pass_register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recomandation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Test_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Test_check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Test_checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total_points")
                        .HasColumnType("float");

                    b.HasKey("Res_id");

                    b.ToTable("engage_resume");
                });

            modelBuilder.Entity("EFEntity.engage_subjects", b =>
                {
                    b.Property<int>("Sub_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correct_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Derivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key_a")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key_b")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key_c")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key_d")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key_e")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sub_id");

                    b.ToTable("engage_subjects");
                });

            modelBuilder.Entity("EFEntity.human_file", b =>
                {
                    b.Property<int>("Huf_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachment_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bonus_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Delete_time")
                        .HasColumnType("datetime2");

                    b.Property<double>("Demand_salaray_sum")
                        .HasColumnType("float");

                    b.Property<int>("File_chang_amount")
                        .HasColumnType("int");

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Human_age")
                        .HasColumnType("int");

                    b.Property<string>("Human_bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Human_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Human_birthplace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_educated_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_educated_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Human_educated_years")
                        .HasColumnType("int");

                    b.Property<string>("Human_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_family_membership")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Human_file_status")
                        .HasColumnType("bit");

                    b.Property<string>("Human_histroy_records")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_party")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_pro_designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_society_security_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hunma_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lastly_change_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Major_change_amount")
                        .HasColumnType("int");

                    b.Property<double>("Paid_salary_sum")
                        .HasColumnType("float");

                    b.Property<DateTime>("Recovery_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruman_id_card")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary_standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Training_amount")
                        .HasColumnType("int");

                    b.HasKey("Huf_id");

                    b.ToTable("human_file");
                });

            modelBuilder.Entity("EFEntity.human_file_dig", b =>
                {
                    b.Property<int>("Hfd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Attachment_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bonus_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Delete_time")
                        .HasColumnType("datetime2");

                    b.Property<double>("Demand_salaray_sum")
                        .HasColumnType("float");

                    b.Property<int>("File_chang_amount")
                        .HasColumnType("int");

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Human_age")
                        .HasColumnType("int");

                    b.Property<string>("Human_bank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Human_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Human_birthplace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_educated_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_educated_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Human_educated_years")
                        .HasColumnType("int");

                    b.Property<string>("Human_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_family_membership")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Human_file_status")
                        .HasColumnType("bit");

                    b.Property<string>("Human_histroy_records")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_party")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_pro_designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_society_security_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hunma_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lastly_change_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Major_change_amount")
                        .HasColumnType("int");

                    b.Property<double>("Paid_salary_sum")
                        .HasColumnType("float");

                    b.Property<DateTime>("Recovery_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruman_id_card")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary_standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Training_amount")
                        .HasColumnType("int");

                    b.HasKey("Hfd_id");

                    b.ToTable("human_file_dig");
                });

            modelBuilder.Entity("EFEntity.major_change", b =>
                {
                    b.Property<int>("Mch_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Change_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Check_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Check_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ihird_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ihird_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_first_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_first_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_salary_standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("New_salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("New_second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary_standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mch_id");

                    b.ToTable("major_change");
                });

            modelBuilder.Entity("EFEntity.salary_grant", b =>
                {
                    b.Property<int>("Sgr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Human_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary_grant_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary_paid_sum")
                        .HasColumnType("float");

                    b.Property<string>("Salary_standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary_standard_sum")
                        .HasColumnType("float");

                    b.Property<string>("Second_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sgr_id");

                    b.ToTable("salary_grant");
                });

            modelBuilder.Entity("EFEntity.salary_grant_details", b =>
                {
                    b.Property<int>("Grd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bouns_sum")
                        .HasColumnType("float");

                    b.Property<double>("Deduct_sum")
                        .HasColumnType("float");

                    b.Property<string>("Human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary_grant_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary_paid_sum")
                        .HasColumnType("float");

                    b.Property<double>("Salary_standard_sum")
                        .HasColumnType("float");

                    b.Property<double>("Sale_sum")
                        .HasColumnType("float");

                    b.HasKey("Grd_id");

                    b.ToTable("salary_grant_details");
                });

            modelBuilder.Entity("EFEntity.salary_standard", b =>
                {
                    b.Property<int>("Ssd_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Change_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Change_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Changer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Check_comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Check_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary_sum")
                        .HasColumnType("float");

                    b.Property<string>("Standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ssd_id");

                    b.ToTable("salary_standard");
                });

            modelBuilder.Entity("EFEntity.salary_standard_details", b =>
                {
                    b.Property<int>("Sdt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Item_id")
                        .HasColumnType("int");

                    b.Property<string>("Item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Standard_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sdt_id");

                    b.ToTable("salary_standard_details");
                });

            modelBuilder.Entity("EFEntity.training", b =>
                {
                    b.Property<int>("Tra_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Check_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Checkstatus")
                        .HasColumnType("int");

                    b.Property<string>("Human_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Human_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_kind_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Regist_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Training_degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Training_hour")
                        .HasColumnType("int");

                    b.Property<string>("Training_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Training_time")
                        .HasColumnType("datetime2");

                    b.HasKey("Tra_id");

                    b.ToTable("training");
                });

            modelBuilder.Entity("EFEntity.users", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_true_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
